using System;
using System.ComponentModel.DataAnnotations;

namespace ICFERApp.Models
{
    public class Student
    {
        [Key]
        public long Id { get; set; }

        private string _autogeneratedNumber;

        public  string StudentRegNo
        {
            get => _autogeneratedNumber;
            set
            {
                _autogeneratedNumber = value;
                _autogeneratedNumber = "BITI-" + Id + "-" + DateTime.Now.Year;
            }
        }

        [Display(Name="First Name")]
        [Required]
        public string FirstName { get; set; }
        [Display(Name="Middle Name")]
        [Required]
        public string MiddleName { get; set; }
        [Display(Name="Last Name")]
        [Required]
        public string LastName { get; set; }
        [Display(Name="Nationality")]
        [Required]
        public string Nationality { get; set; }
        [Display(Name="Gender")]
        [Required]
        public string Gender { get; set; }
        [Display(Name="Religion")]
        [Required]
        public string Religion { get; set; }
        [Display(Name="Medical Condition")]
        [Required]
        public string MedicalCondition { get; set; }
        [Display(Name="Deceased")]
        [Required]
        public string Deceased { get; set; }
        [Display(Name="Home Address")]
        [Required]
        public string HomeAddress { get; set; }
        [Display(Name="Country Of Residence")]
        [Required]
        public string CountryOfResidence { get; set; }
        [Display(Name="City")]
        [Required]
        public string City { get; set; }
        [Display(Name="Date Of Birth")]
        [Required]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}")]
        public DateTime DateOfBirth { get; set; }
        
        [Required]
        public int Age { get; set; }

        public string ImageUrl { get; set; }
        
        public ApplicationUser User { get; set; }
        public string UserId { get; set; }
        public string UserName { get; set; }


        public virtual Parents Parents { get; set; }
        public virtual Education Education { get; set; }
        public virtual Guardian Guardian { get; set; }
        public virtual Siblings Siblings { get; set; }
    }
}